#!/bin/bash

AUTH=""

# check for auth token
if [ -z "$TOKEN_PATH" ]
then
    echo "Info: no token found"
else
    TOKEN=`cat ${TOKEN_PATH}`
    AUTH="?access_token=${TOKEN}"
fi

# TARGET is the sensor being scraped
: ${TARGET_BASE_URL:=wio-mock}
: ${TARGET_BASE_PORT:=8080}
: ${TARGET_BASE_PATH:=v1/node}

: ${TARGET_SENSOR:=GroveTempHumD0}
: ${TARGET_SENSOR_PATH:=temperature}
: ${TARGET_READING_KEY:=celsius_degree}
: ${TARGET_METRIC_GROUP:=iot-fleet-devices}

# Prometheus is the metrics sink
: ${PROMETHEUS_HOST:=localhost}
: ${PROMETHEUS_PORT:=9091}

# Get temp reading
echo "Info: getting ${TARGET_SENSOR}.."
URL="${TARGET_BASE_URL}:${TARGET_BASE_PORT}/${TARGET_BASE_PATH}/${TARGET_SENSOR}/${TARGET_SENSOR_PATH}${AUTH}"

# debug
echo "Debug: URL value is ${URL}"

# Get metric reading
METRIC=$(curl -sSk "${URL}" 2>&1 | jq -r ".${TARGET_READING_KEY}")

# Fail if metric not found
[[ -z "$METRIC" ]] && { echo "Error: METRIC is empty" ; exit 1; }

# push metric to prometheus sink
echo "Info: pushing ${METRIC} to prometheus"
echo "${TARGET_READING_KEY} ${METRIC}" | curl -sS --data-binary @- "${PROMETHEUS_HOST}:${PROMETHEUS_PORT}/metrics/job/${TARGET_METRIC_GROUP}"
